config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'players#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  get '/signup' => 'players#new'
  get '/auth/github/callback' => 'sessions#github_login'
  get '/players/:id/pending_invitations' => 'invitations#index'

  resources :players do
    resources :leagues, :shallow => true
    resources :invitations, :shallow => true
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :league
  belongs_to :player
  scope :pending, -> { where(accepted: false) }
  scope :approved, -> { where(accepted: true) }
  scope :recent, -> { order(created_at: :desc).where(created_at: 1.week.ago..DateTime.now) }

  def league_name
    League.find(self.league_id).name
  end

  def admin_name
    League.find(self.league_id).admin.name
  end

  def player_name
    Player.find(self.player_id).name
  end

  def created_date
    self.created_at.strftime("%A, %b %d")
  end 

end

app/models/league.rb
class League < ApplicationRecord
  belongs_to :admin, :class_name => 'Player'
  has_many :teams
  has_many :invitations
  has_many :players, through: :invitations
  validates :name, presence: true, uniqueness: true
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :invitations
  has_many :leagues, :foreign_key => 'admin_id'
  has_many :teams, through: :leagues
  has_many :leagues, through: :invitations
  validates :name, presence: true, uniqueness: true
  has_secure_password

  def checks_out
      self.password == self.password_confirmation && Player.find_by(:name => self.name) == nil
  end

  def missing_attributes
    age.nil? || nickname.nil? || position.nil? || jersey_number.nil?
  end

  def duplicate_invitation(id)
    invitations.approved.select{ |i| i.league_id == id}.count > 0
  end

  def league_admin
    League.where(:admin => self)
  end

  def recent_invitations
    league_admin.each do |league|
      Invitation.recent.include?(league.invitations)
    end
  end


end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :league
  has_many :players
  accepts_nested_attributes_for :players
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private

  def current_user
    @player ||= Player.find(session[:player_id]) if session[:player_id]
  end

  def require_login
    return head(:forbidden) unless session.include? :player_id
  end

  def logged_in?
    session[:player_id] != nil && session[:player_id] != ""
  end

  def check_cancel
    if params['commit'] == "Cancel"
      redirect_to player_path(current_user)
    end
  end
  
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  include InvitationsHelper
  before_action :require_login
  before_action :check_cancel, only: [:create]

  def index
    current_user
  end

  def new
    current_user
    @invitation = Invitation.new
  end

  def create
      @invitation = Invitation.new(invitations_params)
      if @invitation.save
        flash[:message] = "Invitation successfully sent."
        redirect_to player_path(current_user)
      else
        redirect_to new_player_invitation_path(current_user)
      end
  end

  def update
    @invitation = Invitation.find(params[:id])
    check_duplicates
  end

  def destroy
    @invitation = Invitation.find(params[:id])
    @invitation.delete
    flash[:message] = "Invitation deleted."
    redirect_to player_path(current_user)
  end

  private

  def invitations_params
    params.require(:invitation).permit(:player_id, :league_id, :accepted)
  end

end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :require_login
  before_action :check_cancel, only: [:create, :update]
  before_action :current_user
  skip_before_action :current_user, only: [:new]

  def index
  end

  def new
    @player = Player.find_by(:id => params[:player_id])
    if @player.nil? || @player != current_user
      flash[:message] = "Please use a valid Administrator."
      redirect_to player_path(current_user)
    else
      @league = League.new(:admin_id => params[:player_id])
    end
  end

  def create
    @league = League.new(league_params)
    if @league.save
      redirect_to player_path(@league.admin)
    else
      render 'new'
    end
  end

  def update
    @league = League.find(params[:id])
    @league.update(league_params)
    redirect_to player_path(@league.admin)
  end

  def show
    @league = League.find(params[:id])
  end

  def edit
    @league = League.find(params[:id])
  end

  def destroy
    @league = League.find(params[:id])
    @league.delete
    redirect_to player_path(current_user)
  end

  private

  def league_params
    params.require(:league).permit(:name, :league_type, :schedule, :admin_id)
  end


end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  include PlayersHelper
  before_action :check_cancel, only: [:edit]
  before_action :require_login
  skip_before_action :require_login, only: [:new, :create]

  def new
    if logged_in?
      redirect_to player_path(current_user)
    else
      @player = Player.new
    end
  end

  def create
    @player = Player.new(player_params)
    if @player.checks_out && @player.save
      session[:player_id] = @player.id
      flash[:message] = "Profile successfully created."
      redirect_to player_path(@player)
    else
      render :new
    end
  end

  def destroy
  end

  def show
    current_user
  end

  def edit
    current_user
  end

  def update
    current_user
    @player.update(player_params)
    redirect_to player_path(@player)
  end

  private

  def player_params
    params.require(:player).permit(:name, :age, :nickname, :position, :jersey_number, :admin, :password, :password_confirmation)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  def new
    @player = Player.new
  end

  def create
    @player = Player.find_by(name: params[:name])
    if @player
      return head(:forbidden) unless @player.authenticate(params[:password])
      session[:player_id] = @player.id
      redirect_to player_path(@player)
    else
      redirect_to '/login'
      flash[:message] = "You must create an account to continue."
    end
  end

  def github_login
    @player = Player.find_or_initialize_by(:id => auth['uid']) do |p|
      p.name = auth['info']['name']
    end
    @player.password_digest = SecureRandom.urlsafe_base64
    @player.save
    session[:player_id] = @player.id
    attribute_check
  end

  def destroy
    if logged_in?
      session.delete :player_id
      flash[:message] = "You have successfully logged out."
      redirect_to'/login'
    else
      redirect_to '/login'
    end
  end

  private

  def auth
    request.env['omniauth.auth']
  end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def new
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper

  def check_duplicates
    if current_user.duplicate_invitation(@invitation.league_id)
      @invitation.delete
      flash[:message] = "You already belong to this league."
      redirect_to player_path(current_user)
    else
      @invitation.update(invitations_params)
      redirect_to player_path(current_user)
    end
  end

end

app/helpers/players_helper.rb
module PlayersHelper

  def checks_out?
    @player.password == @player.password_confirmation && Player.find_by(:name => @player.name) == nil
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def attribute_check
    if @player.missing_attributes
      redirect_to edit_player_path(@player)
    else
      redirect_to player_path(@player)
    end
  end

end

app/views/invitations/index.html.erb
<%= render 'players/pending' %>
<%= render 'players/recent' if @player.admin %>

<%= link_to "Back", player_path(@player) %>

app/views/invitations/new.html.erb
<%= form_for([@player, @invitation]) do |f| %>
  <%= f.label :player_id, "Who do you want to send an invite to?" %><br>
  <%= f.collection_select(:player_id, Player.all, :id, :name) %><br>
  <%= f.label :league_id, "Which league is sending the invite?" %><br>
  <%= f.collection_select(:league_id, @player.league_admin.all, :id, :name) %><br>
  <%= f.submit %>
  <%= f.submit "Cancel" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NBA Atlas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <nav>
      <div class='container'>
        <div class='header-style'>
          <h3>NONPROFESSIONAL BASKETBALLER'S ATLAS</h3>
        </div>
      </div>
    </nav>
  </header>
  <body>
    <div class='container'>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: "alert" %>
      <% end %>

      <%= yield %>

    </div>
  </body>
  <footer>
    <nav>
      <div class='container'>
        <div class='nav'>
          <%= link_to "Sign Up", '/signup' %>  <%= link_to "Log In", '/login' %>  <%= link_to 'Log Out', '/logout', method: :post %>  <%= link_to "Home", '/' %>
        </div>
      </div>
    </nav>
  </footer>
</html>

app/views/leagues/_admin_links.html.erb
<h5><%= link_to "Edit League", edit_league_path(@league) %> <%= link_to "Delete League", league_path(@league), method: :delete %></h5>

app/views/leagues/_form.html.erb
<%= render partial: '/players/errors', locals: {obj: @league} %>
<div>
  <%= form_for((@league.new_record? ? [@player, @league] : @league)) do |f| %>
      <%= f.hidden_field :admin_id %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :league_type %>
      <%= f.text_field :league_type %>
      <%= f.label :schedule %>
      <%= f.text_field :schedule %><br>
      <%= f.submit %>
      <%= f.submit "Cancel" %>
  </div>
<% end %>

app/views/leagues/edit.html.erb
<h2>Edit League</h2>
<%= render 'form' %>

app/views/leagues/index.html.erb
<div class="section">
  <h3>Leagues Administered by <%= @player.name %></h3>
</div>
<%= render '/players/admin_leagues' %>

app/views/leagues/new.html.erb
<h2>Create New League</h2>
<%= render 'form' %>

app/views/leagues/show.html.erb
<div class="section">
  <h2><%= @league.name %></h2>
</div>
<ul>
  <li>League Type: <%= @league.league_type %>
  <li>Schedule: <%= @league.schedule %>
  <li>League Admin: <%= @league.admin.name %>
</ul>

<%= render 'admin_links' if @player == @league.admin %>

app/views/players/_admin_leagues.html.erb
<div class='row'>
  <h4 class='eight columns'><%= link_to "Active Leagues as Admin", player_leagues_path(@player) %></h4>
  <div class="four columns">
    <% if @player.league_admin.any? %>
      <% @player.league_admin.each do |league| %>
        <%= link_to "#{league.name}", league_path(league) %><br>
      <% end %>
    <% else %>
      <p>No Leagues currently assigned.</p>
    <% end %>
  </div>
</div>

app/views/players/_admin_show.html.erb
<%= render 'admin_leagues' %>

<h4><%= link_to "Create a new League", new_player_league_path(@player) %></h4>

<div class="section">
  <h2>Recently Sent Invitations</h2>
</div>

<% if @player.recent_invitations %>
  <%= render 'recent' %>
<% else %>
  <p>No recently sent invitations.</p>
<% end %>

<h4><%= link_to "Send New Invitation", new_player_invitation_path(@player) %></h4>

app/views/players/_approved.html.erb
<div class='row'>
  <h4 class="eight columns">Active Leagues as Player</h4>
  <div class="four columns">
    <% if @player.invitations.approved.any? %>
      <% @player.invitations.approved.uniq.each do |i| %>
        <%= link_to "#{i.league.name}", league_path(i.league) %><br>
        <% end %>
      <% else %>
        <p>No active Leagues</p>
    <% end %>
  </div>
</div>

app/views/players/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row" id="error_explanation">
    <h5>
      <%= pluralize(obj.errors.count, "error") %>
      prevented this entry from being saved:
    </h5>

    <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/players/_form.html.erb
  <%= render partial: 'errors', locals: {obj: @player} %>
  <%= form_for @player do |f| %>
    <div class='row'>
      <div class='six columns'>
          <%= f.label :name %>
          <%= f.text_field(:name, class: "u-full-width") %>
      </div>
      <div class='six columns'>
        <%= f.label :nickname %>
        <%= f.text_field(:nickname, class: "u-full-width") %>
      </div>
    </div>
    <div class='row'>
      <div class='four columns'>
        <%= f.label :position %>
        <%= f.text_field(:position, class: "u-full-width") %>
      </div>
      <div class='four columns'>
        <%= f.label :age %>
        <%= f.number_field(:age, class: "u-full-width") %>
      </div>
      <div class='four columns'>
        <%= f.label :jersey_number %>
        <%= f.number_field(:jersey_number, class: "u-full-width") %>
      </div>
    </div>
    <div class='row'>
      <div class='six columns'>
        <%= f.label :password %>
        <%= f.password_field(:password, class: "u-full-width") %>
      </div>
      <div class='six columns'>
        <%= f.label "Confirm Password" %>
        <%= f.password_field(:password_confirmation, class: "u-full-width") %>
      </div>
    </div>
    <div class='row'>
        <%= f.label "Are you a League Administrator?" %>Yes
        <%= f.check_box :admin %>
    </div>
        <%= f.submit %>
        <%= f.submit "Cancel" %>
  <% end %>

app/views/players/_leagues.html.erb
<div class='row'>
  <h4 class='eight columns'><%= link_to "Active Leagues as Admin", player_leagues_path(@player) %></h4>
  <div class="four columns">
    <% if @player.leagues.any? %>
      <% @player.leagues.each do |league| %>
        <%= link_to "#{league.name}", league_path(league) %><br>
      <% end %>
    <% else %>
      <p>No Leagues currently assigned.</p>
    <% end %>
  </div>
</div>

app/views/players/_pending.html.erb
<% if @player.invitations.pending.any? %>
  <ol>
  <% @player.invitations.pending.each do |i| %>
  <li>Invitation Received from <%= i.league_name %> on <%= i.created_date %>, courtesy of <%= i.admin_name %>.
      <%= form_for i do |f| %>
      <div class="row">
        <div class="three columns">
          <%= f.hidden_field :accepted, :value => "1" %>
          <%= button_to "Accept Invitation", i, :method => :post %>
        </div>
        <div class="three columns">
          <%= button_to "Decline Invitation", i, :method => :delete %>
        </div>
      </div>
      <% end %>
  <% end %>
  </ol>
<% else %>
  <p>No pending invitations</p>
<% end %>

app/views/players/_recent.html.erb
<% @player.league_admin.each do |league| %>
  <ul>
    <% league.invitations.recent.each do |i| %>
      <li>Invitation sent from <%= i.league_name %> on <%= i.created_date %> to <%= i.player_name %>.
    <% end %>
  </ul>
<% end %>

app/views/players/edit.html.erb
<h2>Edit <%= @player.name %></h2>
<%= render 'form' %>

app/views/players/new.html.erb
<div class="section">
  <h2> Signup Form </h2>
</div>
<%= render 'form' %>

app/views/players/show.html.erb
<div class="section">
  <h2><%= @player.name %></h2>
</div>
<table class="u-full-width">
  <thead>
    <tr>
      <th>Nickname: </th>
      <th>Age: </th>
      <th>Position: </th>
      <th>Jersey Number: </th>
    <tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @player.nickname %></td>
      <td><%= @player.age %></td>
      <td><%= @player.position %></td>
      <td><%= @player.jersey_number %></td>
    </tr>
    </tbody>
</table>

<h4><%= link_to "Edit Player", edit_player_path(@player) %></h4>

<div class="section">
  <h2>Leagues</h2>
</div>

<%= render 'approved' %>

<%= render 'admin_show' if @player.admin %>

<div class="section">
  <h2>Pending Invitations</h2>
</div>

<%= render 'pending' %>